services:
  funkoshop_fastapi:
    image: funkoshop_fastapi:latest
    container_name: funkoshop_fastapi
    networks:
      - funkoshop_network
    ports:
      - "4000:4000"
    environment:
      - SECRET_KEY=ThisIsNotSecret
      - SQLALCHEMY_DATABASE_URL=mysql+pymysql://USER:PWD@IP_DB:3306/DB_NAME
    command: uvicorn main:app --host 0.0.0.0 --port 4000 --reload

networks:
  funkoshop_network:
    driver: bridge
    enable_ipv6: false
